/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "fileproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(get_device_infoRequest, get_device_infoRequest, AUTO)


PB_BIND(get_device_infoResponse, get_device_infoResponse, AUTO)



