/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "fileproto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(get_device_infoRequest, get_device_infoRequest, AUTO)


PB_BIND(get_device_infoResponse, get_device_infoResponse, AUTO)


PB_BIND(claimRequest, claimRequest, AUTO)


PB_BIND(claimResponse, claimResponse, AUTO)


PB_BIND(reclaimRequest, reclaimRequest, AUTO)


PB_BIND(reclaimResponse, reclaimResponse, AUTO)


PB_BIND(unclaimRequest, unclaimRequest, AUTO)


PB_BIND(unclaimResponse, unclaimResponse, AUTO)


PB_BIND(set_smartledRequest, set_smartledRequest, AUTO)


PB_BIND(set_smartledResponse, set_smartledResponse, AUTO)


PB_BIND(Request, Request, AUTO)


PB_BIND(Response, Response, AUTO)



